# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\joao.andrade\Documents\Py_Diff\Spreadsheet_comparison\sheets.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.select_file_two_button = QtWidgets.QPushButton(Dialog)
        self.select_file_two_button.setGeometry(QtCore.QRect(20, 120, 111, 23))
        self.select_file_two_button.setObjectName("select_file_two_button")
        self.select_file_one_button = QtWidgets.QPushButton(Dialog)
        self.select_file_one_button.setGeometry(QtCore.QRect(20, 10, 111, 23))
        self.select_file_one_button.setObjectName("select_file_one_button")
        self.execute_button = QtWidgets.QPushButton(Dialog)
        self.execute_button.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.execute_button.setObjectName("execute_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 321, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 321, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.select_file_two_button.setText(_translate("Dialog", "Selecionar arquivo 2"))
        self.select_file_one_button.setText(_translate("Dialog", "Selecionar arquivo 1"))
        self.execute_button.setText(_translate("Dialog", "Executar"))
