# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\joao.andrade\Documents\Py_Diff\Spreadsheet_comparison\sheets.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.select_file_two_button = QtWidgets.QPushButton(Dialog)
        self.select_file_two_button.setGeometry(QtCore.QRect(10, 80, 111, 23))
        self.select_file_two_button.setObjectName("select_file_two_button")
        self.select_file_one_button = QtWidgets.QPushButton(Dialog)
        self.select_file_one_button.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.select_file_one_button.setObjectName("select_file_one_button")
        self.execute_button = QtWidgets.QPushButton(Dialog)
        self.execute_button.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.execute_button.setObjectName("execute_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(140, 30, 211, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 231, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 130, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 231, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 161, 16))
        self.label_7.setObjectName("label_7")
        self.help_button = QtWidgets.QPushButton(Dialog)
        self.help_button.setGeometry(QtCore.QRect(220, 250, 75, 23))
        self.help_button.setObjectName("help_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Spreadsheet comparison program"))
        self.select_file_two_button.setText(_translate("Dialog", "Selecionar arquivo 2"))
        self.select_file_one_button.setText(_translate("Dialog", "Selecionar arquivo 1"))
        self.execute_button.setText(_translate("Dialog", "Executar"))
        self.label_3.setText(_translate("Dialog", "Arquivo primário:"))
        self.label_4.setText(_translate("Dialog", "Arquivo secundário:"))
        self.label_5.setText(_translate("Dialog", "Os arquivos são semelhantes?"))
        self.label_6.setText(_translate("Dialog", "Desenvolvido por João Víctor Cesa - TI"))
        self.label_7.setText(_translate("Dialog", "Nome do arquivo a ser gerado:"))
        self.help_button.setText(_translate("Dialog", "Ajuda"))
